//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Бронь.
    /// </summary>
    // *** Start programmer edit section *** (Бронь CustomAttributes)

    // *** End programmer edit section *** (Бронь CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БроньE", new string[] {
            "КодБрони as \'Код брони\'",
            "Комментарий as \'Комментарий\'",
            "Скидка as \'Скидка\'",
            "Ресторан as \'Ресторан\'",
            "Ресторан.Наименование as \'Наименование\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Стол as \'Номер стол\'",
            "Стол.НомерСтола as \'Номер стола\'",
            "Стол.КолвоМест as \'Количество мест за столом\'"}, Hidden=new string[] {
            "Ресторан.Наименование",
            "Сотрудники.ФИО",
            "Стол.НомерСтола"})]
    [AssociatedDetailViewAttribute("БроньE", "Запись", "ЗаписьE", true, "", "Запись", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("БроньE", "Ресторан", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("БроньE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("БроньE", "Стол", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерСтола")]
    [View("БроньL", new string[] {
            "КодБрони as \'Код брони\'",
            "Комментарий as \'Комментарий\'",
            "Скидка as \'Скидка\'",
            "Ресторан.Наименование as \'Наименование ресторана\'",
            "Сотрудники.ФИО as \'ФИО сотрудника\'",
            "Стол.НомерСтола as \'Номер стола\'",
            "Стол.КолвоМест as \'Количество мест за столом\'"})]
    public class Бронь : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодБрони;
        
        private string fКомментарий;
        
        private bool fСкидка;
        
        private IIS.Restoran2.Ресторан fРесторан;
        
        private IIS.Restoran2.Сотрудники fСотрудники;
        
        private IIS.Restoran2.Стол fСтол;
        
        private IIS.Restoran2.DetailArrayOfЗапись fЗапись;
        
        // *** Start programmer edit section *** (Бронь CustomMembers)

        // *** End programmer edit section *** (Бронь CustomMembers)

        
        /// <summary>
        /// КодБрони.
        /// </summary>
        // *** Start programmer edit section *** (Бронь.КодБрони CustomAttributes)

        // *** End programmer edit section *** (Бронь.КодБрони CustomAttributes)
        public virtual int КодБрони
        {
            get
            {
                // *** Start programmer edit section *** (Бронь.КодБрони Get start)

                // *** End programmer edit section *** (Бронь.КодБрони Get start)
                int result = this.fКодБрони;
                // *** Start programmer edit section *** (Бронь.КодБрони Get end)

                // *** End programmer edit section *** (Бронь.КодБрони Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бронь.КодБрони Set start)

                // *** End programmer edit section *** (Бронь.КодБрони Set start)
                this.fКодБрони = value;
                // *** Start programmer edit section *** (Бронь.КодБрони Set end)

                // *** End programmer edit section *** (Бронь.КодБрони Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Бронь.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Бронь.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Бронь.Комментарий Get start)

                // *** End programmer edit section *** (Бронь.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Бронь.Комментарий Get end)

                // *** End programmer edit section *** (Бронь.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бронь.Комментарий Set start)

                // *** End programmer edit section *** (Бронь.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Бронь.Комментарий Set end)

                // *** End programmer edit section *** (Бронь.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Скидка.
        /// </summary>
        // *** Start programmer edit section *** (Бронь.Скидка CustomAttributes)

        // *** End programmer edit section *** (Бронь.Скидка CustomAttributes)
        public virtual bool Скидка
        {
            get
            {
                // *** Start programmer edit section *** (Бронь.Скидка Get start)

                // *** End programmer edit section *** (Бронь.Скидка Get start)
                bool result = this.fСкидка;
                // *** Start programmer edit section *** (Бронь.Скидка Get end)

                // *** End programmer edit section *** (Бронь.Скидка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бронь.Скидка Set start)

                // *** End programmer edit section *** (Бронь.Скидка Set start)
                this.fСкидка = value;
                // *** Start programmer edit section *** (Бронь.Скидка Set end)

                // *** End programmer edit section *** (Бронь.Скидка Set end)
            }
        }
        
        /// <summary>
        /// Бронь.
        /// </summary>
        // *** Start programmer edit section *** (Бронь.Ресторан CustomAttributes)

        // *** End programmer edit section *** (Бронь.Ресторан CustomAttributes)
        [PropertyStorage(new string[] {
                "Ресторан"})]
        [NotNull()]
        public virtual IIS.Restoran2.Ресторан Ресторан
        {
            get
            {
                // *** Start programmer edit section *** (Бронь.Ресторан Get start)

                // *** End programmer edit section *** (Бронь.Ресторан Get start)
                IIS.Restoran2.Ресторан result = this.fРесторан;
                // *** Start programmer edit section *** (Бронь.Ресторан Get end)

                // *** End programmer edit section *** (Бронь.Ресторан Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бронь.Ресторан Set start)

                // *** End programmer edit section *** (Бронь.Ресторан Set start)
                this.fРесторан = value;
                // *** Start programmer edit section *** (Бронь.Ресторан Set end)

                // *** End programmer edit section *** (Бронь.Ресторан Set end)
            }
        }
        
        /// <summary>
        /// Бронь.
        /// </summary>
        // *** Start programmer edit section *** (Бронь.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Бронь.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Restoran2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Бронь.Сотрудники Get start)

                // *** End programmer edit section *** (Бронь.Сотрудники Get start)
                IIS.Restoran2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Бронь.Сотрудники Get end)

                // *** End programmer edit section *** (Бронь.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бронь.Сотрудники Set start)

                // *** End programmer edit section *** (Бронь.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Бронь.Сотрудники Set end)

                // *** End programmer edit section *** (Бронь.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Бронь.
        /// </summary>
        // *** Start programmer edit section *** (Бронь.Стол CustomAttributes)

        // *** End programmer edit section *** (Бронь.Стол CustomAttributes)
        [PropertyStorage(new string[] {
                "Стол"})]
        [NotNull()]
        public virtual IIS.Restoran2.Стол Стол
        {
            get
            {
                // *** Start programmer edit section *** (Бронь.Стол Get start)

                // *** End programmer edit section *** (Бронь.Стол Get start)
                IIS.Restoran2.Стол result = this.fСтол;
                // *** Start programmer edit section *** (Бронь.Стол Get end)

                // *** End programmer edit section *** (Бронь.Стол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бронь.Стол Set start)

                // *** End programmer edit section *** (Бронь.Стол Set start)
                this.fСтол = value;
                // *** Start programmer edit section *** (Бронь.Стол Set end)

                // *** End programmer edit section *** (Бронь.Стол Set end)
            }
        }
        
        /// <summary>
        /// Бронь.
        /// </summary>
        // *** Start programmer edit section *** (Бронь.Запись CustomAttributes)

        // *** End programmer edit section *** (Бронь.Запись CustomAttributes)
        public virtual IIS.Restoran2.DetailArrayOfЗапись Запись
        {
            get
            {
                // *** Start programmer edit section *** (Бронь.Запись Get start)

                // *** End programmer edit section *** (Бронь.Запись Get start)
                if ((this.fЗапись == null))
                {
                    this.fЗапись = new IIS.Restoran2.DetailArrayOfЗапись(this);
                }
                IIS.Restoran2.DetailArrayOfЗапись result = this.fЗапись;
                // *** Start programmer edit section *** (Бронь.Запись Get end)

                // *** End programmer edit section *** (Бронь.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Бронь.Запись Set start)

                // *** End programmer edit section *** (Бронь.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (Бронь.Запись Set end)

                // *** End programmer edit section *** (Бронь.Запись Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БроньE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БроньE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БроньE", typeof(IIS.Restoran2.Бронь));
                }
            }
            
            /// <summary>
            /// "БроньL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БроньL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БроньL", typeof(IIS.Restoran2.Бронь));
                }
            }
        }
    }
}
