//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гости.
    /// </summary>
    // *** Start programmer edit section *** (Гости CustomAttributes)

    // *** End programmer edit section *** (Гости CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостиE", new string[] {
            "КодГостя as \'Код гостя\'",
            "ФИО as \'ФИО\'",
            "Телефон as \'Телефон\'",
            "Скидка as \'Скидка\'",
            "Скидка.Код as \'Уникальный код скидки\'"}, Hidden=new string[] {
            "Скидка.Код"})]
    [MasterViewDefineAttribute("ГостиE", "Скидка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Код")]
    [View("ГостиL", new string[] {
            "КодГостя as \'Код гостя\'",
            "ФИО as \'ФИО\'",
            "Телефон as \'Телефон\'",
            "Скидка.Код as \'Уникальный код скидки\'"})]
    public class Гости : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодГостя;
        
        private string fФИО;
        
        private int fТелефон;
        
        private IIS.Restoran2.Скидка fСкидка;
        
        // *** Start programmer edit section *** (Гости CustomMembers)

        // *** End programmer edit section *** (Гости CustomMembers)

        
        /// <summary>
        /// КодГостя.
        /// </summary>
        // *** Start programmer edit section *** (Гости.КодГостя CustomAttributes)

        // *** End programmer edit section *** (Гости.КодГостя CustomAttributes)
        public virtual int КодГостя
        {
            get
            {
                // *** Start programmer edit section *** (Гости.КодГостя Get start)

                // *** End programmer edit section *** (Гости.КодГостя Get start)
                int result = this.fКодГостя;
                // *** Start programmer edit section *** (Гости.КодГостя Get end)

                // *** End programmer edit section *** (Гости.КодГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.КодГостя Set start)

                // *** End programmer edit section *** (Гости.КодГостя Set start)
                this.fКодГостя = value;
                // *** Start programmer edit section *** (Гости.КодГостя Set end)

                // *** End programmer edit section *** (Гости.КодГостя Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Гости.Телефон CustomAttributes)

        // *** End programmer edit section *** (Гости.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Гости.Телефон Get start)

                // *** End programmer edit section *** (Гости.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Гости.Телефон Get end)

                // *** End programmer edit section *** (Гости.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.Телефон Set start)

                // *** End programmer edit section *** (Гости.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Гости.Телефон Set end)

                // *** End programmer edit section *** (Гости.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Гости.ФИО CustomAttributes)

        // *** End programmer edit section *** (Гости.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Гости.ФИО Get start)

                // *** End programmer edit section *** (Гости.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Гости.ФИО Get end)

                // *** End programmer edit section *** (Гости.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.ФИО Set start)

                // *** End programmer edit section *** (Гости.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Гости.ФИО Set end)

                // *** End programmer edit section *** (Гости.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Гости.
        /// </summary>
        // *** Start programmer edit section *** (Гости.Скидка CustomAttributes)

        // *** End programmer edit section *** (Гости.Скидка CustomAttributes)
        [PropertyStorage(new string[] {
                "Скидка"})]
        [NotNull()]
        public virtual IIS.Restoran2.Скидка Скидка
        {
            get
            {
                // *** Start programmer edit section *** (Гости.Скидка Get start)

                // *** End programmer edit section *** (Гости.Скидка Get start)
                IIS.Restoran2.Скидка result = this.fСкидка;
                // *** Start programmer edit section *** (Гости.Скидка Get end)

                // *** End programmer edit section *** (Гости.Скидка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.Скидка Set start)

                // *** End programmer edit section *** (Гости.Скидка Set start)
                this.fСкидка = value;
                // *** Start programmer edit section *** (Гости.Скидка Set end)

                // *** End programmer edit section *** (Гости.Скидка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиE", typeof(IIS.Restoran2.Гости));
                }
            }
            
            /// <summary>
            /// "ГостиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиL", typeof(IIS.Restoran2.Гости));
                }
            }
        }
    }
}
