//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись.
    /// </summary>
    // *** Start programmer edit section *** (Запись CustomAttributes)

    // *** End programmer edit section *** (Запись CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьE", new string[] {
            "ДатаЗаписи as \'Дата записи\'",
            "Время as \'Время\'",
            "Гости as \'Гости\'",
            "Гости.ФИО as \'ФИО\'",
            "Гости.Телефон as \'Номер телефона гостя\'",
            "Гости.Скидка.Код as \'Уникальный код скидки клиента\'",
            "Гости.Скидка.Процент as \'Процент скидки\'"}, Hidden=new string[] {
            "Гости.ФИО"})]
    [MasterViewDefineAttribute("ЗаписьE", "Гости", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class Запись : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаписи;
        
        private string fВремя;
        
        private IIS.Restoran2.Гости fГости;
        
        private IIS.Restoran2.Бронь fБронь;
        
        // *** Start programmer edit section *** (Запись CustomMembers)

        // *** End programmer edit section *** (Запись CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Время CustomAttributes)

        // *** End programmer edit section *** (Запись.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Время Get start)

                // *** End programmer edit section *** (Запись.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Запись.Время Get end)

                // *** End programmer edit section *** (Запись.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Время Set start)

                // *** End programmer edit section *** (Запись.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Запись.Время Set end)

                // *** End programmer edit section *** (Запись.Время Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (Запись.ДатаЗаписи CustomAttributes)

        // *** End programmer edit section *** (Запись.ДатаЗаписи CustomAttributes)
        public virtual System.DateTime ДатаЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (Запись.ДатаЗаписи Get start)

                // *** End programmer edit section *** (Запись.ДатаЗаписи Get start)
                System.DateTime result = this.fДатаЗаписи;
                // *** Start programmer edit section *** (Запись.ДатаЗаписи Get end)

                // *** End programmer edit section *** (Запись.ДатаЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.ДатаЗаписи Set start)

                // *** End programmer edit section *** (Запись.ДатаЗаписи Set start)
                this.fДатаЗаписи = value;
                // *** Start programmer edit section *** (Запись.ДатаЗаписи Set end)

                // *** End programmer edit section *** (Запись.ДатаЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Гости CustomAttributes)

        // *** End programmer edit section *** (Запись.Гости CustomAttributes)
        [PropertyStorage(new string[] {
                "Гости"})]
        [NotNull()]
        public virtual IIS.Restoran2.Гости Гости
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Гости Get start)

                // *** End programmer edit section *** (Запись.Гости Get start)
                IIS.Restoran2.Гости result = this.fГости;
                // *** Start programmer edit section *** (Запись.Гости Get end)

                // *** End programmer edit section *** (Запись.Гости Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Гости Set start)

                // *** End programmer edit section *** (Запись.Гости Set start)
                this.fГости = value;
                // *** Start programmer edit section *** (Запись.Гости Set end)

                // *** End programmer edit section *** (Запись.Гости Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Restoran2.Бронь.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Бронь CustomAttributes)

        // *** End programmer edit section *** (Запись.Бронь CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Бронь"})]
        public virtual IIS.Restoran2.Бронь Бронь
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Бронь Get start)

                // *** End programmer edit section *** (Запись.Бронь Get start)
                IIS.Restoran2.Бронь result = this.fБронь;
                // *** Start programmer edit section *** (Запись.Бронь Get end)

                // *** End programmer edit section *** (Запись.Бронь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Бронь Set start)

                // *** End programmer edit section *** (Запись.Бронь Set start)
                this.fБронь = value;
                // *** Start programmer edit section *** (Запись.Бронь Set end)

                // *** End programmer edit section *** (Запись.Бронь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьE", typeof(IIS.Restoran2.Запись));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Запись.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗапись CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗапись CustomAttributes)
    public class DetailArrayOfЗапись : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Restoran2.DetailArrayOfЗапись members)

        // *** End programmer edit section *** (IIS.Restoran2.DetailArrayOfЗапись members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Запись by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Запись.
        /// </summary>
        public DetailArrayOfЗапись(IIS.Restoran2.Бронь fБронь) : 
                base(typeof(Запись), ((ICSSoft.STORMNET.DataObject)(fБронь)))
        {
        }
        
        public IIS.Restoran2.Запись this[int index]
        {
            get
            {
                return ((IIS.Restoran2.Запись)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Restoran2.Запись dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
