//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ресторан.
    /// </summary>
    // *** Start programmer edit section *** (Ресторан CustomAttributes)

    // *** End programmer edit section *** (Ресторан CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РесторанE", new string[] {
            "КодРест as \'Код рест\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    [View("РесторанL", new string[] {
            "КодРест as \'Код рест\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    public class Ресторан : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодРест;
        
        private string fНаименование;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (Ресторан CustomMembers)

        // *** End programmer edit section *** (Ресторан CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Ресторан.Адрес CustomAttributes)

        // *** End programmer edit section *** (Ресторан.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Ресторан.Адрес Get start)

                // *** End programmer edit section *** (Ресторан.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Ресторан.Адрес Get end)

                // *** End programmer edit section *** (Ресторан.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ресторан.Адрес Set start)

                // *** End programmer edit section *** (Ресторан.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Ресторан.Адрес Set end)

                // *** End programmer edit section *** (Ресторан.Адрес Set end)
            }
        }
        
        /// <summary>
        /// КодРест.
        /// </summary>
        // *** Start programmer edit section *** (Ресторан.КодРест CustomAttributes)

        // *** End programmer edit section *** (Ресторан.КодРест CustomAttributes)
        public virtual int КодРест
        {
            get
            {
                // *** Start programmer edit section *** (Ресторан.КодРест Get start)

                // *** End programmer edit section *** (Ресторан.КодРест Get start)
                int result = this.fКодРест;
                // *** Start programmer edit section *** (Ресторан.КодРест Get end)

                // *** End programmer edit section *** (Ресторан.КодРест Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ресторан.КодРест Set start)

                // *** End programmer edit section *** (Ресторан.КодРест Set start)
                this.fКодРест = value;
                // *** Start programmer edit section *** (Ресторан.КодРест Set end)

                // *** End programmer edit section *** (Ресторан.КодРест Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Ресторан.Наименование CustomAttributes)

        // *** End programmer edit section *** (Ресторан.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Ресторан.Наименование Get start)

                // *** End programmer edit section *** (Ресторан.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Ресторан.Наименование Get end)

                // *** End programmer edit section *** (Ресторан.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ресторан.Наименование Set start)

                // *** End programmer edit section *** (Ресторан.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Ресторан.Наименование Set end)

                // *** End programmer edit section *** (Ресторан.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РесторанE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РесторанE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РесторанE", typeof(IIS.Restoran2.Ресторан));
                }
            }
            
            /// <summary>
            /// "РесторанL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РесторанL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РесторанL", typeof(IIS.Restoran2.Ресторан));
                }
            }
        }
    }
}
