//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Скидка.
    /// </summary>
    // *** Start programmer edit section *** (Скидка CustomAttributes)

    // *** End programmer edit section *** (Скидка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СкидкаE", new string[] {
            "Код as \'Код\'",
            "Процент as \'Процент\'"})]
    [View("СкидкаL", new string[] {
            "Код as \'Код\'",
            "Процент as \'Процент\'"})]
    public class Скидка : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private int fПроцент;
        
        // *** Start programmer edit section *** (Скидка CustomMembers)

        // *** End programmer edit section *** (Скидка CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Скидка.Код CustomAttributes)

        // *** End programmer edit section *** (Скидка.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Скидка.Код Get start)

                // *** End programmer edit section *** (Скидка.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Скидка.Код Get end)

                // *** End programmer edit section *** (Скидка.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Скидка.Код Set start)

                // *** End programmer edit section *** (Скидка.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Скидка.Код Set end)

                // *** End programmer edit section *** (Скидка.Код Set end)
            }
        }
        
        /// <summary>
        /// Процент.
        /// </summary>
        // *** Start programmer edit section *** (Скидка.Процент CustomAttributes)

        // *** End programmer edit section *** (Скидка.Процент CustomAttributes)
        public virtual int Процент
        {
            get
            {
                // *** Start programmer edit section *** (Скидка.Процент Get start)

                // *** End programmer edit section *** (Скидка.Процент Get start)
                int result = this.fПроцент;
                // *** Start programmer edit section *** (Скидка.Процент Get end)

                // *** End programmer edit section *** (Скидка.Процент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Скидка.Процент Set start)

                // *** End programmer edit section *** (Скидка.Процент Set start)
                this.fПроцент = value;
                // *** Start programmer edit section *** (Скидка.Процент Set end)

                // *** End programmer edit section *** (Скидка.Процент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СкидкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкидкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкидкаE", typeof(IIS.Restoran2.Скидка));
                }
            }
            
            /// <summary>
            /// "СкидкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкидкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкидкаL", typeof(IIS.Restoran2.Скидка));
                }
            }
        }
    }
}
