//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стол.
    /// </summary>
    // *** Start programmer edit section *** (Стол CustomAttributes)

    // *** End programmer edit section *** (Стол CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтолE", new string[] {
            "НомерСтола as \'Номер стола\'",
            "КолвоМест as \'Количество мест\'",
            "Статус as \'Статус\'"})]
    [View("СтолL", new string[] {
            "НомерСтола as \'Номер стола\'",
            "КолвоМест as \'Количество мест\'",
            "Статус as \'Статус\'"})]
    public class Стол : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерСтола;
        
        private int fКолвоМест;
        
        private IIS.Restoran2.Статусы fСтатус;
        
        // *** Start programmer edit section *** (Стол CustomMembers)

        // *** End programmer edit section *** (Стол CustomMembers)

        
        /// <summary>
        /// КолвоМест.
        /// </summary>
        // *** Start programmer edit section *** (Стол.КолвоМест CustomAttributes)

        // *** End programmer edit section *** (Стол.КолвоМест CustomAttributes)
        public virtual int КолвоМест
        {
            get
            {
                // *** Start programmer edit section *** (Стол.КолвоМест Get start)

                // *** End programmer edit section *** (Стол.КолвоМест Get start)
                int result = this.fКолвоМест;
                // *** Start programmer edit section *** (Стол.КолвоМест Get end)

                // *** End programmer edit section *** (Стол.КолвоМест Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стол.КолвоМест Set start)

                // *** End programmer edit section *** (Стол.КолвоМест Set start)
                this.fКолвоМест = value;
                // *** Start programmer edit section *** (Стол.КолвоМест Set end)

                // *** End programmer edit section *** (Стол.КолвоМест Set end)
            }
        }
        
        /// <summary>
        /// НомерСтола.
        /// </summary>
        // *** Start programmer edit section *** (Стол.НомерСтола CustomAttributes)

        // *** End programmer edit section *** (Стол.НомерСтола CustomAttributes)
        public virtual int НомерСтола
        {
            get
            {
                // *** Start programmer edit section *** (Стол.НомерСтола Get start)

                // *** End programmer edit section *** (Стол.НомерСтола Get start)
                int result = this.fНомерСтола;
                // *** Start programmer edit section *** (Стол.НомерСтола Get end)

                // *** End programmer edit section *** (Стол.НомерСтола Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стол.НомерСтола Set start)

                // *** End programmer edit section *** (Стол.НомерСтола Set start)
                this.fНомерСтола = value;
                // *** Start programmer edit section *** (Стол.НомерСтола Set end)

                // *** End programmer edit section *** (Стол.НомерСтола Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Стол.Статус CustomAttributes)

        // *** End programmer edit section *** (Стол.Статус CustomAttributes)
        public virtual IIS.Restoran2.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (Стол.Статус Get start)

                // *** End programmer edit section *** (Стол.Статус Get start)
                IIS.Restoran2.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (Стол.Статус Get end)

                // *** End programmer edit section *** (Стол.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Стол.Статус Set start)

                // *** End programmer edit section *** (Стол.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Стол.Статус Set end)

                // *** End programmer edit section *** (Стол.Статус Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтолE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтолE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтолE", typeof(IIS.Restoran2.Стол));
                }
            }
            
            /// <summary>
            /// "СтолL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтолL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтолL", typeof(IIS.Restoran2.Стол));
                }
            }
        }
    }
}
